---
- name: Include private variables
  include_vars: private.yml

- name: Execute block as sudo
  become: yes
  block:
    - name: Install packages
      apt:
        name="{{ sambasvr_packages }}"
        state=latest

    - name: Unset kerberos default realm
      lineinfile:
        path: /etc/krb5.conf
        regexp: '^(\s*)(default_realm = ATHENA.MIT.EDU)$'
        line: '\1# \2'
        backrefs: yes

    - name: Set kerberos default realm
      blockinfile:
        path: /etc/krb5.conf
        insertafter: '^\s*# default_realm = ATHENA.MIT.EDU$'
        block: |
          #
                  default_realm = {{ krb5_default_realm }}
                  dns_lookup_kdc = true
                  dns_lookup_realm = true
          #

    - name: Set NTP server
      blockinfile:
        path: /etc/systemd/timesyncd.conf
        insertafter: '^#NTP=$'
        block: |
          #
          "NTP={{ timesyncd_ntpsvr }}"
          #
      register: ntpsvr_result
      ignore_errors: True

    - name: Enable NTP
      command: "{{ item }}"
      when: ntpsvr_result is changed
      with_items:
        - timedatectl set-ntp true
        - systemctl restart systemd-timesyncd.service
        - timedatectl --adjust-system-clock

    - name: Create realmd.conf
      template:
        src: realmd.conf
        dest: /etc/realmd.conf

    - name: Update PAM configuration
      command: pam-auth-update --enable mkhomedir
